### PR TITLE
Product Price

### LINKED ISSUE #415: Random "0" appears on category pages
**Describe the bug**
See screenshot 
image

**To Reproduce**
1. Go to a category page
2. Scroll down
3. Notice "0" in the bottom left corner

**Expected behavior**
There shouldn't be any numbers displayed on the bottom left

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser chrome
 - Version 73.0

### LINKED ISSUE #417: Sorting Products by price seems to not work correctly
**What should be changed/improved?**
Products on Category Products page are not ordered by price correctly
image

### PR DESCRIPTION
**Pull request by tutok**
### Please check if the PR fulfills these requirements ###

- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
fix #417
fix #415

**What is the current behavior? (You can also link to an open issue here)**
regular price for Products on Category Products is displayed while when ordering by price, the special price is also taken into account

**What is the new behavior (if this is a feature change)?**
regular and special price is displayed

**Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)**

**Other information:**
to test this PR you need to make sure that `falcon-server` will talk with `magento-23.deity.io`

### CODE REVIEW

File: packages/falcon-magento2-api/src/infrastructure/number.js [hunk 1]
```diff
@@ -0,0 +1,14 @@
+/**
+ * Try to parse provided value to Number.
+ * @param {object} x value to parse
+ * @return {Number|undefined} `Number` if can or `undefined` otherwise
```
Comment (Borales) [inline packages/falcon-magento2-api/src/infrastructure/number.js]:
```suggestion
 * @returns {number|undefined} Number or `undefined` result
```

File: packages/falcon-ecommerce-uikit/src/Product/ProductGallery.tsx [hunk 2]
```diff
@@ -60,10 +56,10 @@ export class ProductGallery extends React.Component<{ items: Item[] }> {
     return (
       <ProductGalleryLayout>
         <Box gridArea="thumbs">
-          {items.map((item, index) => (
+          {items.map((x, index) => (
```
Comment (Borales) [inline packages/falcon-ecommerce-uikit/src/Product/ProductGallery.tsx]: @tutok was `item` a bad name? 😄

File: packages/falcon-magento2-api/src/infrastructure/apollo.js [hunk 3]
```diff
@@ -0,0 +1,20 @@
+/**
+ * Build string representation of Apollo TypeResolver path
+ * @param {{ key: string, prev: { key: string, prev: prev}}} typeResolverPath apollo type resolver path
```
Comment (Borales) [inline packages/falcon-magento2-api/src/infrastructure/apollo.js]: @tutok `prev: prev` is an invalid type, I guess we need to define it via `typedef` and recursive reference

File: packages/falcon-magento2-api/src/index.js [hunk 4]
```diff
@@ -45,15 +47,18 @@ module.exports = class Magento2Api extends Magento2ApiBase {
         weightUnit: () => this.session.weightUnit
       },
       Product: {
-        breadcrumbs: (...args) => this.breadcrumbs(...args)
```
Comment (Borales) [inline packages/falcon-magento2-api/src/index.js]: @tutok what was wrong with `args`? 😄

File: packages/falcon-magento2-api/src/index.js [hunk 5]
```diff
@@ -564,100 +569,135 @@ module.exports = class Magento2Api extends Magento2ApiBase {
 
   /**
    * Reduce product data to what is needed.
-   * @param {object} product - API response from Magento2 backend
+   * @param {object} response - API response from Magento2 backend
```
Comment (Borales) [inline packages/falcon-magento2-api/src/index.js]: @tutok just a question - I see we use both `{object}` and `{Object}` in our jsdocs. Should we simply ignore such cases and use it randomly?

Comment (tutok) [reply packages/falcon-magento2-api/src/index.js]: @Borales so you suggest that I am in charge of that? Ok.

File: packages/falcon-magento2-api/src/index.js (hunk 4 above)
Comment (tutok) [reply packages/falcon-magento2-api/src/index.js]: I remember your disgust with this name (at the office), so I decide to rename. But ok, will revert if you change your mind.

File: packages/falcon-magento2-api/src/index.js (hunk 5 above)
Comment (Borales) [reply packages/falcon-magento2-api/src/index.js]: @tutok we can also include @mateuszwozniak to this conversation 😉 

that was just a question, so in the future, we would know whether we should or we should not check such things - that's all. We could agree on the fact that JSDoc is not that important (code-wise), and we should better concentrate on the code itself.

Comment (tutok) [reply packages/falcon-magento2-api/src/index.js]: will install [this](https://www.npmjs.com/package/eslint-plugin-jsdoc), so this problem will be solved once and forever

File: packages/falcon-magento2-api/src/index.js [hunk 6]
```diff
@@ -564,100 +569,135 @@ module.exports = class Magento2Api extends Magento2ApiBase {
...
+  /**
+   * Resolve Configurable Product Options from Product
+   * @param {Object} parent parent (MagentoProduct or MagentoProductListItem)
+   * @param {Object} args arguments
+   * @param {Object} context context
+   * @param {Object} info info
+   * @return {ConfigurableProductOption} configurable product options
+   */
+  async configurableProductOptions(parent, args, context, info) {
+    const data = typeResolverPathToString(info.path).startsWith('category.products')
```
Comment (mateuszwozniak) [inline packages/falcon-magento2-api/src/index.js]: Can you please add a comment explaining why we check for 'category.products' here, so it's clear for people who don't know the context?

File: packages/falcon-magento2-api/src/infrastructure/number.js [hunk 7]
```diff
@@ -0,0 +1,14 @@
+/**
+ * Try to parse provided value to Number.
```
Comment (mateuszwozniak) [inline packages/falcon-magento2-api/src/infrastructure/number.js]:
```suggestion
 * Try to parse provided value to Number (using Number.parseFloat())
```

File: packages/falcon-magento2-api/src/infrastructure/number.js (hunk 1 above)
Comment (tutok) [reply packages/falcon-magento2-api/src/infrastructure/number.js]: @Borales should not be rather "`Number`" instead of "Number"?

```suggestion
* @returns {number|undefined} `Number` or `undefined` result
```

File: packages/falcon-ecommerce-uikit/src/Locale/Price.tsx [hunk 8]
```diff
@@ -1,24 +1,18 @@
...
-          }).format(value)}
-        </Text>
-      );
-    }}
-  </LocaleContext.Consumer>
+  <Locale>
+    {({ priceFormat }) => (
+      <Text {...rest}>
+        {priceFormat(value, {
+          ...(currency ? { currency } : {}),
```
[the remark this answers is not in the document]
Comment (tutok) [reply packages/falcon-ecommerce-uikit/src/Locale/Price.tsx]: `PriceInnerDom` inherits props from `Price`, while `Price` has the possibility (optional) to overwrite `currency`. Then I need to determine if `currency` is defined because:
```
 Object.assign({ currency: 'USD' }, { currency: undefined });
```
will produce:
```
{currency: undefined}
```

But I reviewed implementation and 
* Improved typing for `PriceInnerDom`
* moved above "merging" code into `priceFormatterFactory`, so client code should not be any more aware of "merging" props

File: packages/falcon-magento2-api/src/infrastructure/number.js (hunk 1 above)
Comment (tutok) [reply packages/falcon-magento2-api/src/infrastructure/number.js]: done

File: packages/falcon-magento2-api/src/infrastructure/number.js [hunk 9]
```diff
@@ -0,0 +1,14 @@
+/**
```
[the remark this answers is not in the document]
Comment (tutok) [reply packages/falcon-magento2-api/src/infrastructure/number.js]: done

File: packages/falcon-magento2-api/src/infrastructure/apollo.js (hunk 3 above)
Comment (tutok) [reply packages/falcon-magento2-api/src/infrastructure/apollo.js]: done

File: packages/falcon-magento2-api/src/index.js (hunk 4 above)
Comment (tutok) [reply packages/falcon-magento2-api/src/index.js]: done

File: packages/falcon-ecommerce-uikit/src/Product/ProductGallery.tsx (hunk 2 above)
Comment (tutok) [reply packages/falcon-ecommerce-uikit/src/Product/ProductGallery.tsx]: done

File: packages/falcon-ecommerce-uikit/src/Product/Product.tsx [hunk 10]
```diff
@@ -182,7 +184,29 @@ export class Product extends React.PureComponent<{ product: any }> {
...
+                      <React.Fragment>
+                        <Price fontSize="xl" variant="old" mr="xs" value={product.price.regular} />
+                        <Price fontSize="xl" variant="special" value={product.price.special} />
+                      </React.Fragment>
+                    ) : (
+                      <Price fontSize="xl" value={product.price.regular} />
+                    )}
+                    <Locale>
+                      {({ priceFormat }) =>
+                        (product.tierPrices || []).map(x => (
```
[the remark this answers is not in the document]
Comment (tutok) [reply packages/falcon-ecommerce-uikit/src/Product/Product.tsx]: done
